name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby:
        - 2.4
        - 2.5
        - 2.6
        - 2.7

    name: Ruby ${{ matrix.ruby }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundle-cache: true
      - name: Run Test
        run: bundle exec rake test
