name: Test

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Run Test
        run: bundle exec rake test
