name: Test

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby:
        - 2.2.x
        - 2.3.x
        - 2.4.x
        - 2.5.x
        - 2.6.x

    name: Ruby ${{ matrix.ruby }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Bundler
        run: gem install bundler -v '~>1.14'

      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Run Test
        run: bundle exec rake test
